#pull official mysql image
FROM mysql:latest

#set environment variables
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase

#copy the initialization script to the container
COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3307